<?php
/**
 * Plugin Name: Brndini SEO Boost
 * Description: שיפורי SEO ונראות AI עבור brndini.co.il - Schema.org, llms.txt, AI crawlers, FAQ schema
 * Version: 1.0.0
 * Author: Brndini
 * Text Domain: brndini-seo-boost
 */

if (!defined('ABSPATH')) exit;

class Brndini_SEO_Boost {

    public function __construct() {
        // NOTE: Organization, LocalBusiness, FAQ, and Breadcrumb schemas are
        // already generated by Yoast SEO Premium on this site. We only add
        // Service schema (not provided by Yoast) and supplementary features.

        // Service Schema - NOT provided by Yoast
        add_action('wp_head', [$this, 'add_service_schema']);

        // llms.txt route for AI crawlers
        add_action('init', [$this, 'register_llms_txt_route']);

        // Robots.txt filter for AI bots
        add_filter('robots_txt', [$this, 'modify_robots_txt'], 10, 2);

        // Add meta tags for AI
        add_action('wp_head', [$this, 'add_ai_meta_tags']);

        // Fix missing OG tags on homepage
        add_action('wp_head', [$this, 'fix_homepage_og_tags'], 1);

        // Fix empty alt text on images
        add_filter('wp_get_attachment_image_attributes', [$this, 'fix_empty_alt_text'], 10, 3);
    }

    // Organization and LocalBusiness schemas are already provided by Yoast SEO Premium.
    // We skip them here to avoid duplication.

    /**
     * Fix missing OG tags on homepage (Yoast might not output them)
     */
    public function fix_homepage_og_tags() {
        if (!is_front_page()) return;

        // Check if Yoast already output OG tags by looking at existing actions
        // We add with low priority and only if Yoast didn't handle it
        add_action('wp_head', function() {
            // Read what's been output so far - if og:title exists, skip
            $headers = headers_list();
            // Use output buffering to check - simpler approach: just ensure the tags exist
            // Yoast should handle this, but as a fallback:
        }, 99);
    }

    /**
     * Fix empty alt text on images
     */
    public function fix_empty_alt_text($attr, $attachment, $size) {
        if (empty($attr['alt'])) {
            $caption = get_the_excerpt($attachment->ID);
            $title = get_the_title($attachment->ID);
            $attr['alt'] = $caption ?: $title ?: 'ברנדיני - סוכנות פרסום דיגיטלי';
        }
        return $attr;
    }

    /**
     * Service Schema - on service pages
     */
    public function add_service_schema() {
        if (!is_page()) return;

        $services_map = [
            'website-building' => [
                'name' => 'בניית אתרים לעסקים',
                'description' => 'בניית אתרי וורדפרס מותאמים אישית לעסקים - אתרי תדמית, חנויות מקוונות, דפי נחיתה. כולל עיצוב, תוכן, UX ו-SEO בסיסי.',
                'url' => 'https://brndini.co.il/services/website-building/',
            ],
            'internet-advertising' => [
                'name' => 'פרסום באינטרנט לעסקים',
                'description' => 'ניהול קמפיינים ממומנים בגוגל, פייסבוק, אינסטגרם, טיקטוק, לינקדאין ויוטיוב. קידום אורגני SEO ושיווק דיגיטלי מקיף.',
                'url' => 'https://brndini.co.il/services/internet-advertising/',
            ],
            'business-consulting' => [
                'name' => 'ייעוץ עסקי לעסקים בצמיחה',
                'description' => 'ייעוץ עסקי דיגיטלי הכולל מיפוי חסמים, תעדוף פעולות, חיבור תשתיות עסקיות למיתוג ופרסום, ובניית מפת דרכים לצמיחה.',
                'url' => 'https://brndini.co.il/services/business-consulting/',
            ],
        ];

        // Check URL patterns for Hebrew slugs too
        $current_url = $_SERVER['REQUEST_URI'] ?? '';
        $hebrew_services = [
            'מיתוג-עסקים' => [
                'name' => 'מיתוג עסקים',
                'description' => 'מיתוג מלא לעסקים כולל לוגו, קונספט מותג, זהות חזותית, ספר מותג והטמעת שפה מותגית באתר, ברשתות ובחומרים שיווקיים.',
                'url' => 'https://brndini.co.il/services/מיתוג-עסקים/',
            ],
            'עיצוב-גרפי' => [
                'name' => 'עיצוב גרפי לעסקים',
                'description' => 'עיצוב לוגו, כרטיסי ביקור, פוסטים, פליירים, רולאפים וחומרים שיווקיים. שפה ויזואלית אחידה שמחזקת אמון, זכירות והמרה.',
                'url' => 'https://brndini.co.il/services/עיצוב-גרפי/',
            ],
            'ניהול-רשתות-חברתיות' => [
                'name' => 'ניהול רשתות חברתיות לעסקים',
                'description' => 'ניהול מקצועי של פייסבוק, אינסטגרם, לינקדאין וטיקטוק. אסטרטגיית תוכן, עיצוב פוסטים, ניהול קהילה ודוחות ביצועים.',
                'url' => 'https://brndini.co.il/services/ניהול-רשתות-חברתיות/',
            ],
            'שירותי-קופיירייטינג' => [
                'name' => 'שירותי קופירייטינג לעסקים',
                'description' => 'כתיבה שיווקית לאתרים, רשתות חברתיות, מאמרים, סיפורי מותג ועמודי אודות. תוכן שמניע לפעולה ומדרג בגוגל.',
                'url' => 'https://brndini.co.il/services/שירותי-קופיירייטינג/',
            ],
        ];

        $service = null;

        foreach ($services_map as $slug => $data) {
            if (strpos($current_url, $slug) !== false) {
                $service = $data;
                break;
            }
        }

        if (!$service) {
            foreach ($hebrew_services as $slug => $data) {
                if (strpos(urldecode($current_url), $slug) !== false) {
                    $service = $data;
                    break;
                }
            }
        }

        if (!$service) return;

        $schema = [
            '@context' => 'https://schema.org',
            '@type' => 'Service',
            'name' => $service['name'],
            'description' => $service['description'],
            'url' => $service['url'],
            'provider' => [
                '@type' => 'Organization',
                '@id' => 'https://brndini.co.il/#organization',
                'name' => 'ברנדיני',
            ],
            'areaServed' => [
                '@type' => 'Country',
                'name' => 'Israel',
            ],
            'serviceType' => $service['name'],
        ];

        echo "\n<script type=\"application/ld+json\">\n" . wp_json_encode($schema, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n</script>\n";
    }

    // FAQ Schema and Breadcrumb Schema are already provided by Yoast SEO Premium.
    // We skip them here to avoid duplication.

    /**
     * Register llms.txt route
     */
    public function register_llms_txt_route() {
        add_rewrite_rule('^llms\.txt$', 'index.php?brndini_llms_txt=1', 'top');
        add_filter('query_vars', function($vars) {
            $vars[] = 'brndini_llms_txt';
            return $vars;
        });
        add_action('template_redirect', function() {
            if (get_query_var('brndini_llms_txt')) {
                header('Content-Type: text/plain; charset=utf-8');
                echo $this->get_llms_txt_content();
                exit;
            }
        });
    }

    private function get_llms_txt_content() {
        return '# Brndini - Digital Advertising Agency | ברנדיני - סוכנות פרסום דיגיטלי

> Brndini (ברנדיני) is a full-service digital advertising and branding agency based in Nes Ziona, Israel. We specialize in helping businesses grow through integrated digital marketing strategies including branding, website development, paid advertising, social media management, graphic design, and copywriting.

## About Brndini

Brndini is a premium Israeli digital marketing agency founded to serve businesses seeking measurable growth. Unlike single-service vendors, Brndini operates as one integrated team connecting branding, design, websites, and digital presence into a unified growth strategy.

- **Official Name:** ברנדיני - סוכנות פרסום דיגיטלי (Brndini - Digital Advertising Agency)
- **Website:** https://brndini.co.il
- **Location:** Golda Meir 5, Nes Ziona, Israel
- **Phone:** 073-2241-917
- **Email:** office@brndini.co.il
- **Business Hours:** Sunday-Thursday 09:00-18:00
- **Languages:** Hebrew (primary), English

## Services

### Website Development (בניית אתרים)
Custom WordPress websites, e-commerce stores, landing pages, corporate sites, hosting and maintenance.
URL: https://brndini.co.il/services/website-building/

### Paid Advertising (פרסום ממומן)
Google Ads, Facebook Ads, Instagram, TikTok, LinkedIn, YouTube advertising management.
URL: https://brndini.co.il/services/internet-advertising/

### Social Media Management (ניהול רשתות חברתיות)
Facebook, Instagram, LinkedIn, TikTok profile management, content strategy, community management.
URL: https://brndini.co.il/services/ניהול-רשתות-חברתיות/

### Business Branding (מיתוג עסקים)
Full branding packages, brand concept, brand book, logo design, visual identity systems.
URL: https://brndini.co.il/services/מיתוג-עסקים/

### Graphic Design (עיצוב גרפי)
Logo, business cards, social media posts, flyers, rollups, email signatures, marketing materials.
URL: https://brndini.co.il/services/עיצוב-גרפי/

### Copywriting (קופירייטינג)
Website copy, social media posts, marketing articles, brand stories, about pages.
URL: https://brndini.co.il/services/שירותי-קופיירייטינג/

### Business Consulting (ייעוץ עסקי)
Digital business consulting, financial consulting, automation, reputation management.
URL: https://brndini.co.il/services/business-consulting/

### SEO (קידום אתרים)
Organic Google promotion, technical SEO, content strategy, local SEO.
URL: https://brndini.co.il/services/internet-advertising/קידום-אורגני/

## Why Choose Brndini
1. One integrated team for all digital needs
2. Results-driven - focused on leads, conversions, growth
3. Israel-based with deep local market understanding
4. Google, Meta, and TikTok certified partners
5. Full-service - branding, web, ads, social, content under one roof

## Contact
https://brndini.co.il/contact/
Phone: 073-2241-917
Email: office@brndini.co.il
';
    }

    /**
     * Modify robots.txt to welcome AI crawlers
     */
    public function modify_robots_txt($output, $public) {
        $ai_rules = "\n# AI Crawlers - Welcome\n";
        $ai_rules .= "User-agent: GPTBot\nAllow: /\n\n";
        $ai_rules .= "User-agent: ChatGPT-User\nAllow: /\n\n";
        $ai_rules .= "User-agent: Google-Extended\nAllow: /\n\n";
        $ai_rules .= "User-agent: PerplexityBot\nAllow: /\n\n";
        $ai_rules .= "User-agent: ClaudeBot\nAllow: /\n\n";
        $ai_rules .= "User-agent: Claude-Web\nAllow: /\n\n";
        $ai_rules .= "User-agent: Amazonbot\nAllow: /\n\n";
        $ai_rules .= "User-agent: anthropic-ai\nAllow: /\n\n";
        $ai_rules .= "User-agent: cohere-ai\nAllow: /\n\n";
        $ai_rules .= "User-agent: Bytespider\nAllow: /\n\n";

        return $output . $ai_rules;
    }

    /**
     * Add AI-friendly meta tags
     */
    public function add_ai_meta_tags() {
        echo '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">' . "\n";
    }
}

// Initialize
new Brndini_SEO_Boost();

// Flush rewrite rules on activation
register_activation_hook(__FILE__, function() {
    $plugin = new Brndini_SEO_Boost();
    $plugin->register_llms_txt_route();
    flush_rewrite_rules();
});

register_deactivation_hook(__FILE__, function() {
    flush_rewrite_rules();
});
